version: '2'
services:
    node:
        image: node:8
        environment:
            - NODE_ENV=development
        volumes:
            - ./app:/usr/src/app
        ports:
            - "3000:3000"
        depends_on:
            - mongo
        working_dir: /usr/src/app
        command: "node /usr/src/app/index.js" # "npm install"  
    mongo: 
        image: mongo:3
        ports:
            - "27017:27017"
        volumes:
            - ./mongo:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: 1234
    mongo-express:
        image: 'mongo-express:latest'
        depends_on:
            - mongo
        ports:
            - '8081:8081'  
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: admin
            ME_CONFIG_MONGODB_ADMINPASSWORD: 1234          